export const USERS = [
    {
        id: 0,
        name: 'Pompom',
        email: 'test@gmail.com',
        password: 'Test12345!',
        race: 'alchimiste',
        points: 150,
        victories: 15,
        defeates: 1,
        friends: [1, 2, 3],
    },
    {
        id: 1,
        name: 'Pompom2',
        email: 'test@gmail.com',
        password: 'Test12345!',
        race: 'enchanteur',
        points: 145,
        victories: 17,
        defeates: 10,
        friends: [],
    },
    {
        id: 2,
        name: 'Pompom3',
        email: 'test@gmail.com',
        password: 'Test12345!',
        race: 'guerrier',
        points: 135,
        victories: 8,
        defeates: 1,
        friends: [],
    },
    {
        id: 3,
        name: 'Pompom4',
        email: 'test@gmail.com',
        password: 'Test12345!',
        race: 'espion',
        points: 125,
        victories: 14,
        defeates: 8,
        friends: [],
    },
    {
        id: 4,
        name: 'Pompom5',
        email: 'test@gmail.com',
        password: 'Test12345!',
        race: 'alchimiste',
        points: 115,
        victories: 10,
        defeates: 4,
        friends: [],
    },
    {
        id: 5,
        name: 'Pompom6',
        email: 'test@gmail.com',
        password: 'Test12345!',
        race: 'espion',
        points: 105,
        victories: 8,
        defeates: 4,
        friends: [],
    },
    {
        id: 6,
        name: 'Pompom7',
        email: 'test@gmail.com',
        password: 'Test12345!',
        race: 'sorcier',
        points: 741,
        victories: 145,
        defeates: 14,
        friends: [],
    },
    {
        id: 7,
        name: 'Pompom8',
        email: 'test@gmail.com',
        password: 'Test12345!',
        race: 'alchimiste',
        points: 1000,
        victories: 105,
        defeates: 45,
        friends: [],
    }

]
