export const USERS = [
    {
        id: 0,
        name: 'Pompom',
        email: 'test@gmail.com',
        password: 'Test12345!',
        role: 'sorcier',
        score: 150,
        victory: 15,
        loose: 1,
        friend: [1],
    },
    {
        id: 1,
        name: 'Pompom2',
        email: 'test@gmail.com',
        password: 'Test12345!',
        role: 'enchanteur',
        score: 145,
        victory: 17,
        loose: 10,
        friend: [],
    },
    {
        id: 2,
        name: 'Pompom3',
        email: 'test@gmail.com',
        password: 'Test12345!',
        role: 'guerrier',
        score: 135,
        victory: 8,
        loose: 1,
        friend: [],
    },
    {
        id: 3,
        name: 'Pompom4',
        email: 'test@gmail.com',
        password: 'Test12345!',
        role: 'espion',
        score: 125,
        victory: 14,
        loose: 8,
        friend: [],
    },
    {
        id: 4,
        name: 'Pompom5',
        email: 'test@gmail.com',
        password: 'Test12345!',
        role: 'alchimiste',
        score: 115,
        victory: 10,
        loose: 4,
        friend: [],
    },
    {
        id: 5,
        name: 'Pompom6',
        email: 'test@gmail.com',
        password: 'Test12345!',
        role: 'espion',
        score: 105,
        victory: 8,
        loose: 4,
        friend: [],
    },
    {
        id: 6,
        name: 'Pompom7',
        email: 'test@gmail.com',
        password: 'Test12345!',
        role: 'sorcier',
        score: 741,
        victory: 145,
        loose: 14,
        friend: [],
    },
    {
        id: 7,
        name: 'Pompom8',
        email: 'test@gmail.com',
        password: 'Test12345!',
        role: 'alchimiste',
        score: 1000,
        victory: 105,
        loose: 45,
        friend: [],
    }

]
